### ISSUE TITLE
Login with facebook

### ISSUE THREAD

**Issue by sayed19** [delight-im/Android-DDP#104]
I am working on an android app where I need to login with facebook credentials. But there is no method for doing so. How to over come this issue?

**Comment by mwaclawek** [comment]
Thanks for your feature request!

There have been discussions about the Facebook login in https://github.com/delight-im/Android-DDP/issues/84 and https://github.com/delight-im/Android-DDP/issues/21 already. Maybe @romaluca can share his solution or provide some hints on what to do.

Basically, you have to create the login handler for Facebook yourself (at least until someone shared their code here). This requires a few lines on the server (JavaScript) and a few lines in your app (Android). The examples referenced in `Extensions.md` may be helpful.
