### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by proft** [delight-im/Android-DDP#110]
Hello!

I have model with photo field. 
How I can upload photo from Android client to Meteor.js server?
Thanks!

**Comment by proft** [comment]
Bump ...

**Comment by mwaclawek** [comment]
Thanks, good question!

That's definitely not the primary use case for Meteor, so support for file uploads is not as good as one would wish.

One solution might be to convert the files to Base64 on the client side (using JavaScript), sending them to the server, and decoding (or just storing) them there.

Some links that may be helpful:

 * http://stackoverflow.com/questions/10099202/how-would-one-handle-a-file-upload-with-meteor
 * http://stackoverflow.com/questions/27934141/meteor-uploading-file-from-client-to-mongo-collection-vs-file-system-vs-gridfs
 * https://medium.com/@victorleungtw/how-to-upload-files-with-meteor-js-7b8e811510fa
 * https://github.com/VeliovGroup/Meteor-Files
 * https://github.com/tomitrescak/meteor-uploads
 * https://www.codetutorial.io/meteor-server-file-upload/

Apart from that, sorry, there's not much more this library can do for you at the moment. To a great extend, it's a Meteor core issue.

**Comment by proft** [comment]
Thanks for response! 
I thought about base64 ... but stick to POST :)
