### ISSUE TITLE
How to use android-ddp with requery

### ISSUE THREAD

**Issue by richieroldan** [delight-im/Android-DDP#132]
Can you please give me an example on how to use requery https://github.com/requery/requery  with this library. Thank you.

**Comment by ocram** [comment]
Sorry, don't know anything about "requery", so cannot help with it.

If you implement [these interfaces](https://github.com/delight-im/Android-DDP/tree/81f0b8c573540a386dba16e92328ea731be10d4d/Source/library/src/main/java/im/delight/android/ddp/db), however, you can make *anything* work as a database for this library.
