### ISSUE TITLE
How to call methods with array of objects with keys

### ISSUE THREAD

**Issue by jahirfiquitiva** [delight-im/Android-DDP#141]
On the Meteor side, there's some code similar to this:

```
const data = [{
            item: 1,
            email: "something",
            name: "John Doe"
          }];
		  
connector.ddpclient.call('method', data, (err, success) => {
	// Code
}
```

The method will check the items in the array just like:
`data.item`, `data.email`, `data.name` ....

How can I call that method with the named items?

The current `call` method only accepts a simple array of objects, so I cannot use a `HashMap` or something :/

Thanks in advance

**Comment by ocram** [comment]
In JavaScript you don’t have that `HashMap` / map / dictionary / object only, either. You first have an array and then, inside that, your map. Why not do the same on Android? The data types are documented in the README.
