### ISSUE TITLE
Any listener (or method) to find out if all the subscribed data was received from server?

### ISSUE THREAD

**Issue by smahdis** [delight-im/Android-DDP#148]
Imagine I have a collection with 100 (or any other number of) documents on the server.

I subscribe to this collection and everything is good. 

But the problem is that I want to set a listener for when all these 100 documents are received.

When I start subscription, a loading is shown to the user but I don't know when to hide the loading because I don't know if all the data is received.

**Comment by ocram** [comment]
Isn’t that what the `onSuccess` method of the `SubscribeListener` callback tells you? You can pass that callback to the `subscribe` method. Let me know if that helps.

**Comment by smahdis** [comment]
Yep, that's exactly what I was seeking for. 

Sorry for the stupid question.
