### ISSUE TITLE
Android-DDP is going logout when received any update

### ISSUE THREAD

**Issue by adam-jack-2** [delight-im/Android-DDP#16]
I have an interesting issue. Android-DDP is going logout and close socket connection when any data come with update.

How can i fix it? Thank you.

**Comment by mwaclawek** [comment]
Thanks! That would be strange, and definitely wrong, you're right.

Unfortunately, we cannot reproduce this yet. Could you share some code that causes this to happen?

Please also check that the error is not in your code, and that you set up (and nested) the calls to the client correctly.
