### ISSUE TITLE
How does this compare to android-ddp-client?

### ISSUE THREAD

**Issue by stephen-workpop** [delight-im/Android-DDP#19]
How does Android-DDP compare to android-ddp-client? Do both libraries have the same features? I am considering making a switch from android-ddp-client to this library, but I want to make sure that its features are on par first. 

See: https://github.com/kenyee/android-ddp-client

I know this isn't an "issue", I just couldn't find any other way to contact the developer.

**Comment by mwaclawek** [comment]
Good question, thanks!

I've not really taken a closer look at the other library, unfortunately. But if you're a user of that library, you probably know best what features it has and how it works.

So please feel free to ask about any features or the workflow here, and I'll do my best to answer.

Generally, the "Usage" section of this project's README is probably the best point to start:
https://github.com/delight-im/Android-DDP#usage

We can then leave this thread open to collect all information that is relevant to this comparison.

**Comment by stephen-workpop** [comment]
I am considering making the switch from android-ddp-client to your library. It looks very clean and lightweight. I see that you are pretty active on this project and have made quite a few contributions recently, which is also a plus. Do you plan on continuing to make contributions to this library on a regular basis and providing support for the foreseeable future? Or is this just a side project on the back burner that isn't that high of a priority? I would hate to switch to this library only to have development cease and support dropped a day later.

**Comment by mwaclawek** [comment]
You are welcome to making the switch!

As I said, this library *probably* has all the features that you need, but I can't say for sure. So please be careful and try things first without spending too much work on this right away :)

I absolutely *do* plan to continue working on this library and have *no* plans to stop support. But obviously, I cannot give any support guarantee. (Neither does the other library, however, I guess.) Sorry!

So I'll do my best to continue providing good support for this library and maybe the community can help as well if some problems occur. That's all I can offer ;)
