### ISSUE TITLE
Add source files to android-ddp-0.0.1-bundle.jar

### ISSUE THREAD

**Issue by mikosik** [delight-im/Android-DDP#2]
It would help in development of apps that use Android-DDP, if `android-ddp-0.0.1-bundle.jar` contained also source files of Android-ddp library. This way one could easily peek how given library class is implemented.

If you prefer to keep sources outside of bundle jar, consider providing separate android-ddp-0.0.1-bundle-src.jar with sources only.

**Comment by mwaclawek** [comment]
Thanks! You're right, that would be useful.

Another JAR that includes the sources should have been introduced with https://github.com/delight-im/Android-DDP/commit/fa7822d7c2a0c948b768ccbb7b609afa7cc1aa3b now.

Please try again with the `*-src` JAR and confirm whether it works or not.

**Comment by mikosik** [comment]
Thanks for so quick fix!

However for now I cannot use the lib as I realize it doesn't support wss as autobahn library used by it internally doesn't have that support as described here https://github.com/tavendo/AutobahnAndroid/issues/8

**Comment by mwaclawek** [comment]
Thank you!

Tracking the SSL issue [here](https://github.com/delight-im/Android-DDP/issues/3) from now on :)
