### ISSUE TITLE
Subscription with args

### ISSUE THREAD

**Issue by RevMen** [delight-im/Android-DDP#22]
It looks like it's currently not possible to create a subscription using arguments, and you must always subscribe to a publication that has no arguments.  Is that correct?

[As in arg1, arg2...](http://docs.meteor.com/#/full/meteor_subscribe)

If this is the case, it would be very beneficial to add that functionality.  I think it's pretty typical to subscribe to a subset of documents based on some chosen value so that an entire collection is not sent over the wire.

**Comment by RevMen** [comment]
Oops, I just poked through the source and saw that it is implemented.  It's just not in the docs (that I saw).

This works like expected:
`String subscriptionID = mMeteor.subscribe("collection", new Object[]{"arg1"});`

**Comment by mwaclawek** [comment]
The documentation has been updated in https://github.com/delight-im/Android-DDP/commit/ac77e746f2fd4b9c6deee0245e46dd4094cc6d4c

Thank you!
