### ISSUE TITLE
ECONNREFUSED (Connection refused)

### ISSUE THREAD

**Issue by katopz** [delight-im/Android-DDP#26]
Hi guys,

I'm testing on local `ws://192.168.2.133:3000/websocket` and everything working fine 
but got stuck with real server which is Ubuntu 14 on DigitalOcean via MUP. `ws://128.199.207.81:3000/websocket`
```
onDisconnect : failed to connect to /128.199.207.81 (port 3000) after 6000ms: isConnected failed: ECONNREFUSED (Connection refused)
```
client js version `128.199.207.81` is working fine btw, so any hint would be appreciated.

Thanks

**Comment by katopz** [comment]
NVM, seem like `PORT` is mess up.

**Comment by mwaclawek** [comment]
Just wanted to follow up on this issue: Have you been able to make this work in the end?

What was wrong? The port?

**Comment by katopz** [comment]
Hi @mwaclawek 

It's about DigitalOcean+Nginx+MUP+SSL issue I think as ref here https://github.com/arunoda/meteor-up/issues/100

I'm building just a prototype so I will stick with port 5000 (anything that not 80)
(have to config with mup json setting) as workaround 
and plan to revisit it again after mupx is release there.

Cheers
