### ISSUE TITLE
Another example

### ISSUE THREAD

**Issue by chuchivic** [delight-im/Android-DDP#31]
Hi!

I've done another example of a todo list hosted here:

http://todoandroidddp.meteor.com/

With login, add tasks, receive it reactively and now working in delete, if you don't mind I can upload into a branch or a pull request to master :)

And I'm thinking about to develop offline feature with Realm (https://realm.io/) for the tasks model as example too.

**Comment by mwaclawek** [comment]
Thanks for this!

So you could get all features working on Android with this library? That's great :)

It's kind of you to offer us to include this example. But we actually don't want to keep any server-side resources in this repository. This project should only be about the client-side things on Android.

The `Server` directory is just there for basic testing and may be removed in the future.

Developing offline support for Android with Realm would be super interesting, by the way!
