### ISSUE TITLE
Method errors without a "reason" are not parsed correctly

### ISSUE THREAD

**Issue by michaelstephendavies** [delight-im/Android-DDP#32]
At [Protocol.java:84](https://github.com/delight-im/Android-DDP/blob/master/Android/Source/src/im/delight/android/ddp/Protocol.java#L84) you check for `Protocol.Field.REASON` where I assume you meant `Protocol.Field.ERROR`. This means that if the error has an `error` field but not a `reason` field, the `error` is incorrectly `null`.

**Comment by mwaclawek** [comment]
Thank you so much! You're absolutely right, of course :)

Should be fixed with https://github.com/delight-im/Android-DDP/commit/3a3b15305165bbee3bc60c802efa38924f1b61db
