### ISSUE TITLE
Maven 

### ISSUE THREAD

**Issue by kordianbruck** [delight-im/Android-DDP#34]
Would be awesome, if one could get the source code directly via maven. 

Currently it is kinda messy to include the source code as a separate module in android studio.

**Comment by mwaclawek** [comment]
Thank you!

I don't really think adding a JAR in Android Studio is that messy or difficult (anymore):

 * http://stackoverflow.com/questions/16608135/android-studio-add-jar-as-library
 * https://commonsware.com/blog/2015/01/16/getting-jar-into-android-studio.html

Regarding Maven, you're probably referring to this, right?

 * https://maven.apache.org/guides/mini/guide-central-repository-upload.html
 * http://stackoverflow.com/questions/28846802/how-to-manually-publish-jar-to-maven-central

**Comment by kordianbruck** [comment]
Well yes, a JAR works fine, but if you want to publish your app open source, other people should be able to just download the source code and all dependencies will also be then downloaded automatically. I am not sure if this works with Autobahn in this project, but it make the usage way easier.

Check out this blog article for a proper explanation:
http://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en

**Comment by mwaclawek** [comment]
Thanks, I see your point.

I will look into this, but it may take some time. Sorry!

Leaving this issue open until it's done :)

**Comment by jitpack-io** [comment]
Hi

Would be very easy publish Android-DPP as a maven library on JitPack.io. All that's needed is a Gradle build file. Happy to submit a PR if you're interested. 
https://jitpack.io/#delight-im/Android-DDP

**Comment by mwaclawek** [comment]
@jitpack-io Yes, please feel free to submit a pull request! This will allow us to judge if using your service is indeed more convenient while still fulfilling the requirements. Maybe it will solve the Maven issue for us :)

**Comment by jitpack-io** [comment]
Ok great, submitted PR #45. To publish a new version simply add a GitHub release. That's it:)

**Comment by mwaclawek** [comment]
Can someone please try if you can include this library as a Maven dependency in Gradle now?

 * Declare the Gradle repository in your root `build.gradle`

   ```gradle
   allprojects {
       repositories {
           maven { url "https://jitpack.io" }
       }
   }
   ```

 * Declare the Gradle dependency in your app module's `build.gradle`

   ```gradle
   dependencies {
       compile 'com.github.delight-im:Android-DDP:413cd62cb6'
   }
   ```

**Comment by kordianbruck** [comment]
@mwaclawek Yes - works like a charm! Thanks!

**Comment by mwaclawek** [comment]
The README has been updated with the Gradle dependency information:
https://github.com/delight-im/Android-DDP/blob/59e79b8e19c9ac74c7e428fa1bb4d50fc9b00b4a/README.md#installation

Thanks for testing, @kordianbruck, and thanks for providing this service, @jitpack-io!
