### ISSUE TITLE
Publish JARS?

### ISSUE THREAD

**Issue by 67726e** [delight-im/Android-DDP#36]
Any reason against publishing the JARs to Sonatype? I realize it's a pain in the ass, but I'd be more than happy to lend a hand getting things setup if you're amenable to the idea.

**Comment by mwaclawek** [comment]
Help would definitely be appreciated :) Thank you!

So if you can assist, please do :) There seems to be much more interest in this issue than expected.

Let's keep the discussion here, though: https://github.com/delight-im/Android-DDP/issues/34
