### ISSUE TITLE
Methods from Accounts Package.

### ISSUE THREAD

**Issue by cpagr** [delight-im/Android-DDP#37]
Hi,

I'm trying to call Accounts.callLoginMethod method from my Android device. But, I get an error: 404, Method not found.

Is there a possible way to call a method from a different package or is it a feature yet to be implemented?

Thanks, in advance.

**Comment by mwaclawek** [comment]
Thanks for your question!

Not sure if you should really need to call this method. But anyway, this is not built into this library directly.

Nevertheless, you can easily make this work. You can call *any* method that your Meteor server exposes via the following command:

```java
mMeteor.call("myMethod");
```

All the internal methods are implemented like this as well. If you want to see how it's done, here's [an example](https://github.com/delight-im/Android-DDP/blob/db48d9e1663a603048a3e7c71bf0422b3502fdf7/Android/Source/src/im/delight/android/ddp/Meteor.java#L641).

Now you only have to find out the method names that you can call. You can get a list of all available method names by putting the following piece of code into your server files and watching the console:

```javascript
Meteor.startup(function () {
    console.log(Object.keys(Meteor.server.method_handlers).sort());
});
```

Does this help?
