### ISSUE TITLE
Question: how to get the initial collection items?

### ISSUE THREAD

**Issue by grago** [delight-im/Android-DDP#38]
This must be a very dumb question, but how can i get all the initial collection items after subscribing to it?

I've looked into the onSuccess callback of the SubscribeListener but i didn't have any luck.

Thanks.

**Comment by iahvector** [comment]
You will receive them automatically in the onDataAdded callback passed to the meteor singleton. Make Sure to check that the data wsa not added before as you'll receive them again each time you login.

**Comment by mwaclawek** [comment]
@grago There are no dumb questions :)

@iahvector Thanks for helping out!
