### ISSUE TITLE
Set Up server and Connect To Localhost

### ISSUE THREAD

**Issue by isdzulqor** [delight-im/Android-DDP#41]
how to sett up server for this library, I made an android native app with this library and I use meteor for my web service. I dont remove insecure package and autopublish package. so I can Insert, delete and update without subscribe or call the method in client.
but my problem is I can not connect to my localhost. I use genymotion for the android emulator.
Any one can Help me, please,,, Thank you for this amazing library
It's my first time work with Web Socket,,
here is my code https://ideone.com/pXzJW8

**Comment by isdzulqor** [comment]
[SOLVED] I change my Server Uri in my native java
Before ws://192.168.56.1:3000
to be like this ws://192.168.56.1:3000/websocket

**Comment by mwaclawek** [comment]
Thanks!

Actually, the connection URL is documented like that, with the `/websocket` suffix, isn't it?

Do you feel any part of the documentation is unclear or should be improved?
