### ISSUE TITLE
WebSockets protocol violation : onDissconnect

### ISSUE THREAD

**Issue by daupawar** [delight-im/Android-DDP#43]
i am getting error 'WebSockets protocol violation' when i use "MeteorSingleton.getInstance().loginWithEmail"

log stack trace
Meteor
System.out:   send
System.out:     message == {"msg":"method","id":"cf4114bb-126d-458d-a8f3-70f6c4ae43b8","params":[{"password":"mypassword","user":{"email":"user@mail.com"}}],"method":"login"}
System.out:     dispatching
 WebSocketException (de.tavendo.autobahn.WebSocketException: RSV != 0 and no extension negotiated)
.WebSocketReader: ended
WebSocketConnection: fail connection [code = 4, reason = WebSockets protocol violation
WebSocketReader: quit
WebSocketWriter: ended
System.out: Meteor
System.out:   onClose
System.out:     code == 4
System.out:     reason == WebSockets protocol violation
System.out: MeteorSingleton
System.out:   onDisconnect
System.out:     code == 4
System.out:     reason == WebSockets protocol violation
MainActivity: WebSockets protocol violation

**Comment by mwaclawek** [comment]
Thanks!

That's really strange, as it seems to be a problem with the well-tested WebSocket library that is used internally.

What server are you connecting to? Is it something like `your-example.meteor.com`?

**Comment by daupawar** [comment]
Thank for the reply 
Android-DDP is great lib.
issue is resolved. problem was with my connection url, i changed my url "localhost:3000/websocket" to "(myipadress):3000/websocket" now its working fine
thanks
