### ISSUE TITLE
Move to gradle

### ISSUE THREAD

**Issue by Arjun-sna** [delight-im/Android-DDP#48]
I see the project is not under Gradle build system. 
Can we migrate this to gradle ?

**Comment by Arjun-sna** [comment]
@mwaclawek may I know why this pull request [https://github.com/delight-im/Android-DDP/pull/45] is not merged.

**Comment by mwaclawek** [comment]
The switch to Gradle *will* be done, but I cannot give any specific timeframe, yet.

Anyway, if this issue is solved by doing that switch, that pull request will be merged as well, probably.

Until then, you should not have any significant disadvantages as a user of this library.

**Comment by kordianbruck** [comment]
Other than being a pain to main and update the related files. 

Also inhibits contributions as it makes it way harder for Android developers to get started.

**Comment by mwaclawek** [comment]
@kordianbruck Regarding your first line, what exactly are you referring to? Regarding the second one, you're somewhat right, of course. As I said, the switch *will* be done.

**Comment by kordianbruck** [comment]
@mwaclawek referring to the lack of automatic updates of the source code if you reference it directly. Every time I want update, I need to redo the gradle stuff ;)

**Comment by mwaclawek** [comment]
@kordianbruck So just to get this right: You're *not* simply including the JAR in Android Studio (which is possible) but adding Gradle support to the project yourself every time you update?

**Comment by kordianbruck** [comment]
@mwaclawek Pretty much, yes. Now that you write it out loud it sounds really stupid, but I need to compile it from source.

**Comment by mwaclawek** [comment]
@kordianbruck Is there any reason you can't use the JARs (and must instead compile from source every time)?

**Comment by mwaclawek** [comment]
Migrated in https://github.com/delight-im/Android-DDP/commit/413cd62cb66c781e1e85c24dece26ce16ddeefcd
