### ISSUE TITLE
What's the diffrerence between Meteor and MeteorSingleton? How to increase lifetime of connection?

### ISSUE THREAD

**Issue by Rokeder** [delight-im/Android-DDP#51]
What's the diffrerence between Meteor and MeteorSingleton? For example:

If i will initialize variable like this:
Meteor mMeteor = new MeteorSingleton.createInstance(this,"some_web_socket");
Is it right implementation? If not what case will be right?

**Comment by mwaclawek** [comment]
Thanks for your question!

Singleton access should be well-documented in the README:
https://github.com/delight-im/Android-DDP/blob/76bde3f493a5fcf8ac0c4ef79d99911eca30a9e3/README.md#usage

If you don't know what the [Singleton pattern](https://en.wikipedia.org/wiki/Singleton_pattern) is for, you may not really need it, perhaps.

Usually, the normal usage is what you need. But when you need to access the same `Meteor` instance from multiple `Activity` instances, for example, you may find the singleton useful.

If using the singleton, you call `createInstance(...)` only once. Afterwards, you have to call `getInstance()` or just use the instance that you assigned to your variable (`mMeteor`).

Does that help?
