### ISSUE TITLE
An graphql client (ported from lokka) for meteor with Android DDP as transport

### ISSUE THREAD

**Issue by harisvsulaiman** [delight-im/Android-DDP#52]
https://github.com/harisvsulaiman/Lokka-java

**Comment by mwaclawek** [comment]
Thanks for sharing!

Is it feature complete? Does it work as expected? Or is it a work in progress?

**Comment by harisvsulaiman** [comment]
Work in progress

**Comment by mwaclawek** [comment]
Okay, please get back to us in this issue when it's finished. Maybe, we should reference your work in the `Extensions.md` file then.
