### ISSUE TITLE
¿What is the function of Meteor.setLoggingEnabled(true);?

### ISSUE THREAD

**Issue by cristianhoyos66** [delight-im/Android-DDP#55]
I need to know what is the real work for this line

**Meteor.setLoggingEnabled(true);**

Thanks

**Comment by Rokeder** [comment]
It shows you all the operations(in the Log of Android Studio) that appears in interaction of server and your application.

**Comment by mwaclawek** [comment]
Exactly. If you have some problem with your client-server communication that you don't understand, you may use this setting to debug things. But otherwise, you won't need it. Anyway, only use it during development.

**Comment by cristianhoyos66** [comment]
Ok guys, thank you :)
