### ISSUE TITLE
Can I call two publish?

### ISSUE THREAD

**Issue by cristianhoyos66** [delight-im/Android-DDP#58]
I need to do something like this:

```
 // server
 BlogPosts = new Mongo.Collection('posts');
 
Meteor.publish('posts-current-user', function publishFunction() {
   return BlogPosts.find({author: this.userId}, {sort: {date: -1}, limit: 10});
 }
 Meteor.publish('posts-by-user', function publishFunction(who) {
   return BlogPosts.find({authorId: who._id}, {sort: {date: -1}, limit: 10});
 }

 // client
 Meteor.subscribe('posts-current-user');
 Meteor.subscribe('posts-by-user', someUser);

```

I do this because in meteor in the client use minimongo and the collections are overlaped if publish return data from the same collection.

¿Can I do the same thing or is there a better way to do this with Android-DDP?

Thank you.

**Comment by mwaclawek** [comment]
The behaviour should be the same in your JavaScript client and on Android using this library. So for best practices on how to write your server-side code, please refer to the various Meteor resources online. This is not something that is related to this library.

But if you encounter any problems, e.g. the data that you receive on Android is not what you receive in JavaScript (when using these two publications), please report this here.

**Comment by cristianhoyos66** [comment]
Ok man, thank you very much
