### ISSUE TITLE
Version 2.1.0 bug

### ISSUE THREAD

**Issue by Rokeder** [delight-im/Android-DDP#59]
This is Meteor Server code:
/Finish method
finishAppByCourier: function(appToFinish) {
check(this.userId, String);
check(appToFinish, String);
var userId = this.userId;
Applications.update(appToFinish, 
{ $set: 
{
factDeliverDateTime: new Date(),
status: 'finished'
}
});
var app = Applications.findOne(appToFinish);
if(Meteor.isServer){
Meteor.call('addToHistory', app, userId, 'courierFinishApp');
if(app.client.androidRegId)
Meteor.call('sendPushClientUser', app.client.androidRegId, 'Request is done!');
}
return {
success: true
};

This is android:

Login.mMeteor.call("finishAppByCourier",new Object[]{Login.dataList.get(i).get("documentID").toString()});

This algorithm is to "finish" order(when you finish order on mobile it also finish on the server and vise versa), But i get no log(it means no response) from the server when i finish order in mobile application. So on the server it finished, in mobile application it didn't finish. In verions 1.0.1 it works correctly.

UPDATE:

Also when i have to get data from server(i subscribed) i get NO DATA, no response, no log.

**Comment by mwaclawek** [comment]
Thanks for describing this problem!

What is the actual thing you're trying to do and the thing you're expecting in terms of this library's API calls?

You're trying to execute a method using `mMeteor.call` and then you are expecting a response? Are you expecting the response in a `ResultListener` or via data that should be received in `onDataAdded`?

By the way, are you testing this on an emulator or on a real device?

**Comment by Rokeder** [comment]
finish - replace a json object from one publication to another. It doesn't work.
About UPDATE: I just try to subscribe and get data from the publications. And it also doesn't work.

**Comment by mwaclawek** [comment]
@Rokeder Unless you answer the questions (most importantly the last two questions), we won't be able to help. Sorry!
