### ISSUE TITLE
android

### ISSUE THREAD

**Issue by guoyoujin** [delight-im/Android-DDP#7]
hey Can you give an android client and server interaction implementation example of add and delete

**Comment by mwaclawek** [comment]
The [example](https://github.com/delight-im/Android-DDP/blob/master/Examples/DDP/src/im/delight/android/ddp/examples/MainActivity.java) that is linked to from the main page has code for inserting, updating and deleting data.

The responses from the server are handled in the callbacks that are implemented in that `Activity` as well. How to implement things on the server is not related to this library, however.

That's what you were interested in, right? Does this answer the question?

**Comment by guoyoujin** [comment]
I want to know the android DDP whether can realize like a meteor. It was such a hot js code push, thank you for giving me to reassure

**Comment by mwaclawek** [comment]
Adding, updating and deleting data is definitely possible. You should read the official Meteor documentation to see how to configure the server and what code to use on the server. And the examples linked in the previous reply show how to communicate with the server from Android.

Do you have any more questions regarding this topic? Can we close this issue?

**Comment by guoyoujin** [comment]
ok
