### ISSUE TITLE
how to subscribe data from server

### ISSUE THREAD

**Issue by daniel6435** [delight-im/Android-DDP#76]
Hi,

i like to subscribe data from server to android, is it possible?
how can i do? 

> String subscriptionId = mMeteor.subscribe("publicMessages");

Thanks

**Comment by cristianhoyos66** [comment]
Yes, you can do it with that and consequently adding a callback using this:  ``` mMeteor.addCallback(this); ```

**Comment by mwaclawek** [comment]
@cristianhoyos66 Thank you so much for helping out :)

@daniel6435 Is there anything left that you haven't understood after reading @cristianhoyos66's explanation and after having read the issue he referenced?

**Comment by romaluca** [comment]
Hi, is possible changes parameter in the subscribe?
i need to do something like this:
[http://www.meteorpedia.com/read/Infinite_Scrolling](http://www.meteorpedia.com/read/Infinite_Scrolling)
So i have to implement this:

```
Deps.autorun(function() {
    Meteor.subscribe('items', Session.get('itemsLimit'));
  });

```
Is possible with android-ddp recall a subscript with a different parameter (in my case the parameter is the limit of items)?
Thanks!

**Comment by mwaclawek** [comment]
@romaluca Well, as written in the README, the following is how to pass a parameter to a subscription:

```java
myMeteor.subscribe("my-subscription", new Object[] { myLimit });
```

Since you subscribe *once*, you can't pass changing values, can you? As far as I can see, the only way to change the limit is to subscribe again with a different value.

**Comment by daniel6435** [comment]
Thanks @mwaclawek  and  @cristianhoyos66 for answer my question, i already get the subscribed result from my collection, but is there possible to know the size of my collection(how many list of data in my collection)?

**Comment by mwaclawek** [comment]
@romaluca If you wanted to know whether the subscription will automatically re-run as soon as it notices that the parameter's value has changed, that's not possible. Sorry! This kind of reactivity is only available in the official JavaScript client of Meteor.

@daniel6435 If you want to know the size, you either have to wait until all documents have been received (the `SubscribeListener` of your `subscribe` call will be fired) and then count how many documents you have received. Or you have to define a method on your server, e.g. `countMyDocuments` that returns the count directly from the database. On Android, you could then call that method.

**Comment by daniel6435** [comment]
@mwaclawek  how to i know when it received all document?

**Comment by mwaclawek** [comment]
@daniel6435 You can find an example here: https://github.com/delight-im/Android-DDP/issues/65
