### ISSUE TITLE
no method

### ISSUE THREAD

**Issue by guoyoujin** [delight-im/Android-DDP#8]
mMeteor.call("/auto", new ResultListener() {
			
			@Override
			public void onSuccess(String result) {
				Log.e("TAG", "result=========="+result);
				
			}
			
			@Override
			public void onError(String error, String reason, String details) {
				// TODO Auto-generated method stub
				Log.e("TAG", "error=========="+error);
				Log.e("TAG", "reason=========="+reason);
				Log.e("TAG", "details=========="+details);
				
			}
		});

why reason==========Method not found   error==========404

**Comment by mwaclawek** [comment]
Well, as the error message explains, you probably didn't implement the `auto` on the server. Did you?

Moreover, the slash at the beginning is only needed when accessing collections, e.g. `mMeteor.call("/my-collection/count");`.

So you might change your code to `mMeteor.call("auto", ...);` and implement the `auto` method on the server. There's an [example for that](https://github.com/delight-im/Android-DDP/blob/master/Server/android-ddp-meteor.js#L123) as well.

Does that help?

**Comment by guoyoujin** [comment]
Yes, I follow the steps you implement this feature, thank you
