### ISSUE TITLE
Compile 3.1.0 library bug

### ISSUE THREAD

**Issue by Rokeder** [delight-im/Android-DDP#81]
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/NOTICE
	File1: C:\Users\User\.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-core-asl\1.9.7\2dd41e7570f5c73e63a6a1311671a60c817e1989\jackson-core-asl-1.9.7.jar
	File2: C:\Users\User\.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-mapper-asl\1.9.7\3bc2efad5ceb9e24e44f731d4282b5df3ea6d23f\jackson-mapper-asl-1.9.7.jar

I just followed the instructions. Just change 0 to 1 in build.gradle; It occurs when i try to build it to a real device.

**Comment by romaluca** [comment]
After upgrade i have the same problem

**Comment by mwaclawek** [comment]
Sorry for that!

Can you try `5dc75991ff805e9187b3329cef20c779b6143ec9` instead of `v3.1.0`?

**Comment by thingbreaker** [comment]
still getting same error with 5dc75991ff805e9187b3329cef20c779b6143ec9

**Comment by elloyg** [comment]
Hi !
I'm getting the same error. And Since v3.0.0 I'm getting another exception on pre-lollipop devices wich, I think, is related to this one : 

```
java.lang.NoClassDefFoundError: org.codehaus.jackson.map.ObjectMapper
    at im.delight.android.ddp.Meteor.<clinit>(Meteor.java:49)
```

**Comment by romaluca** [comment]
the problem persists

**Comment by mwaclawek** [comment]
@Rokeder @romaluca @thingbreaker @elloyg Sorry!

Please try the following dependency instead:

`compile 'com.github.delight-im:Android-DDP:1cc95b77585bee8f6da56fb87943bcf63892a2f7'`

**Comment by romaluca** [comment]
now it works! thanks!

**Comment by mwaclawek** [comment]
@romaluca and @thingbreaker Thanks a lot for testing this!

The README has been updated and you should be able to use the latest release `v3.1.1` now.

@elloyg Does the latest release solve your `NoClassDefFoundError` problem? I didn't encounter any problems on pre-Lollipop devices.

**Comment by thingbreaker** [comment]
@mwaclawek sorry it is maybe out of topic, but where i should put new database feature? i put it on onConnect method but the result is empty array

**Comment by elloyg** [comment]
@mwaclawek No the latest build didn't resolves it, but the compilation works now, thanks for this fix !
I think this `NoClassDefFoundError` is here because of others libraries I use... I'm trying to find which one/ones is/are conflicting with Android-DDP and Jackson.

**Comment by mwaclawek** [comment]
@thingbreaker Have you read the documentation in the README already? There should be some detailed examples. If you still have questions, please just open a separate issue.

@elloyg Thanks a lot! Let's track your issue here: https://github.com/delight-im/Android-DDP/issues/86
