### ISSUE TITLE
NoClassDefFoundError: org.codehaus.jackson.map.ObjectMapper

### ISSUE THREAD

**Issue by mwaclawek** [delight-im/Android-DDP#86]
From https://github.com/delight-im/Android-DDP/issues/81:

> Since v3.0.0 I'm getting another exception on pre-lollipop devices wich, I think, is related to this one :
>
> `java.lang.NoClassDefFoundError: org.codehaus.jackson.map.ObjectMapper at im.delight.android.ddp.Meteor.<clinit>(Meteor.java:49)`
>
> I think this NoClassDefFoundError is here because of others libraries I use... I'm trying to find which one/ones is/are conflicting with Android-DDP and Jackson.
>
>  I'm getting this error when using Android Facebook SDK library at the same time as Android DDP

-- @elloyg

**Comment by elloyg** [comment]
Hi !
After some research I found that the problem was caused by a misconfiguration of mine implementing multiDex.
Thanks for your help ;)

**Comment by mwaclawek** [comment]
@elloyg Great that it isn't a bug here in this library :) Thank you!
