### ISSUE TITLE
problem with Gradle build

### ISSUE THREAD

**Issue by krishnav39** [delight-im/Android-DDP#88]
hi, when i am trying to build gradle this shows an error like :

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.delight-im:Android-DDP:v3.1.2.
     Required by:
         meteortest:app:unspecified
      > Could not resolve com.github.delight-im:Android-DDP:v3.1.2.
         > Could not get resource 'https://jitpack.io/com/github/delight-im/Android-DDP/v3.1.2/Android-DDP-v3.1.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/delight-im/Android-DDP/v3.1.2/Android-DDP-v3.1.2.pom'.
               > peer not authenticated

please guide me where i do wrong.

**Comment by mwaclawek** [comment]
Thanks for your question!

It appears there is a problem with SSL/TLS connections on your computer.

Can you try changing `https` to `http` in the following repository definition?

```
maven { url "https://jitpack.io" }
```

Obviously, it would be better to fix the SSL/TLS certificate problems than to use plain HTTP, though.

**Comment by krishnav39** [comment]
hi,

i changed like but still it through an error

maven { url "http://jitpack.io <https://jitpack.io/>" }



Error:(34, 13) Failed to resolve: com.github.delight-im:Android-DDP:v3.1.2
<a href="openFile">Show in File</a><br><a
href="open.dependency.in.project.structure">Show in Project Structure
dialog</a>

**Comment by mwaclawek** [comment]
Well, has that been the complete error message already?

Can you try updating Gradle or make sure Java 8 is installed? Or maybe you can try one of the following resources:

 * http://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse
 * http://stackoverflow.com/questions/26734738/android-studio-gradle-build-failed-errorcause-peer-not-authenticated
