### ISSUE TITLE
what do when internet connection is lost

### ISSUE THREAD

**Issue by romaluca** [delight-im/Android-DDP#89]
Do the library manage automatically the lost of internet connection?
It tries to reconnect or i have to manage this situation?

Thanks

**Comment by mwaclawek** [comment]
Thanks for your question!

There's some support for this situation built-in already:

 1. It should try to re-connect automatically ([here](https://github.com/delight-im/Android-DDP/blob/7ee9d8b5eb58253fbcd17062847356efa2100667/Source/library/src/main/java/im/delight/android/ddp/Meteor.java#L155)). There's an open issue regarding this feature: https://github.com/delight-im/Android-DDP/issues/62
 2. It should queue all messages that couldn't be sent to the server yet and wait for the connection to be established again, then send everything ([here](https://github.com/delight-im/Android-DDP/blob/7ee9d8b5eb58253fbcd17062847356efa2100667/Source/library/src/main/java/im/delight/android/ddp/Meteor.java#L197)). There's an open issue regarding this feature: https://github.com/delight-im/Android-DDP/issues/61

As you see, this should really be handled by this library, it shouldn't be your task to do this. If things are not working as expected yet, let's fix and improve them.
