### ISSUE TITLE
It works only with wifi

### ISSUE THREAD

**Issue by romaluca** [delight-im/Android-DDP#90]
hi, i'm trying my app on my phone. When it is connected to wifi all work. But when it is connected on 3g i the meteor connection not works. 
And it return this error:

```
04-27 13:46:53.583 425-425/com.shuttertop.app E/METEOR: Exception!!!!
04-27 13:46:53.583 425-425/com.shuttertop.app W/System.err: com.firebase.tubesock.WebSocketException: IO Error
04-27 13:46:53.584 425-425/com.shuttertop.app W/System.err:     at com.firebase.tubesock.WebSocketReceiver.run(WebSocketReceiver.java:78)
04-27 13:46:53.584 425-425/com.shuttertop.app W/System.err:     at com.firebase.tubesock.WebSocket.runReader(WebSocket.java:372)
04-27 13:46:53.584 425-425/com.shuttertop.app W/System.err:     at com.firebase.tubesock.WebSocket.access$000(WebSocket.java:30)
04-27 13:46:53.584 425-425/com.shuttertop.app W/System.err:     at com.firebase.tubesock.WebSocket$2.run(WebSocket.java:108)
04-27 13:46:53.584 425-425/com.shuttertop.app W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-27 13:46:53.584 425-425/com.shuttertop.app W/System.err: Caused by: java.io.EOFException
04-27 13:46:53.585 425-425/com.shuttertop.app W/System.err:     at libcore.io.Streams.readFully(Streams.java:83)
04-27 13:46:53.585 425-425/com.shuttertop.app W/System.err:     at java.io.DataInputStream.readFully(DataInputStream.java:99)
04-27 13:46:53.585 425-425/com.shuttertop.app W/System.err:     at com.firebase.tubesock.WebSocketReceiver.read(WebSocketReceiver.java:141)
04-27 13:46:53.585 425-425/com.shuttertop.app W/System.err:     at com.firebase.tubesock.WebSocketReceiver.run(WebSocketReceiver.java:34)
04-27 13:46:53.585 425-425/com.shuttertop.app W/System.err: 	... 4 more
04-27 13:46:53.585 425-425/com.shuttertop.app I/METEOR: disconnected!!!!
```

in my manifest i have:
`<uses-permission android:name="android.permission.INTERNET" />`

Do you have any solution?
Thanks!

**Comment by mwaclawek** [comment]
That's strange. Thanks!

This library (and its WebSocket library) really shouldn't care what technology is used to establish an internet connection. All they need is connectivity, no matter what way.

Can anybody confirm or disprove this problem/bug?

**Comment by romaluca** [comment]
it was a bug of my cm13! in debug mode in my phone doesn't work

Thanks!

**Comment by mwaclawek** [comment]
What a relief! Good to hear it's not a bug in this library :) Thanks!

**Comment by TingaZ** [comment]
Hi

Did you guys find a solution to this problem, cause I'm about to deploy my app to the GooglePlayStore but it still cannot connect using mobile internet but it does only with wifi?

**Comment by ocram** [comment]
@TingaZ I don't think there's any bug in this library here, so there's nothing to fix.

> it was a bug of my cm13! in debug mode in my phone doesn't work

**Comment by TingaZ** [comment]
Yeah, it wasn't any bug but just a matter of allowing background data on
Google Play Service on my device.
