### ISSUE TITLE
Problem with managing json using InmemoryDatabase

### ISSUE THREAD

**Issue by musafirkhana** [delight-im/Android-DDP#97]
I have a json like this.` { "role" : { "id" : 3, "name" : "Customer" } }`
How to i get the value "name" from document.
I am using `database.getCollection(collectionName).getDocument(documentId).getField("role");` for getting role its return me role={id=3,name=Customer}

How can i manage that ?
Thanks

**Comment by cristianhoyos66** [comment]
Hi, you can see this issue #94 that I did some days ago. I have not closed that because I have not proved the last answer from @mwaclawek, but I think that you can do it with your example.

**Comment by mwaclawek** [comment]
Yes, thanks for helping @cristianhoyos66!

@musafirkhana Please follow the code example from the linked issue and report your findings here. What you did so far is correct. The solution is to know that the field that you retrieved in the end corresponds to the data type that you saved there in JavaScript, i.e. on the Meteor server.

 * If you saved a string in JavaScript, the field is of type `String` in Java.
 * If you saved a number in JavaScript, the field is of type `Integer`, `Long`, `Float` or `Double` in Java.
 * If you saved a boolean in JavaScript, the field is of type `Boolean` in Java.
 * If you saved an object (`{}`) in JavaScript, the field is of type `Map<String, Object>` in Java. This should be what you have here.
 * If you saved an array (`[]`) in JavaScript, the field is of type `List<Object>` or `Object[]` in Java. I'm not sure, you have to try this.

Hope that helps!
